const TOGGLE_APP_LOADING = 'TOGGLE_APP_LOADING';
const RESET_APP_LOADING = 'RESET_APP_LOADING';

const HOME_ACTIONS = {
  SET_CITY_WEATHER: 'SET_CITY_WEATHER',
  SET_CITY_ERROR_MESSAGE: 'SET_CITY_ERROR_MESSAGE'
};

export default {
  TOGGLE_APP_LOADING,
  RESET_APP_LOADING,
  HOME_ACTIONS
};
